REST API додаток
AndriiBeznosov/nodejs-homework-rest-api pull request #1
Opened 2023-01-07 21:54 UTC by AndriiBeznosov

Привіт. З Новим Роком!
Відправляю дз hw2 на перевірку.
Перевірь, будь ласка.

2023-01-07 22:24 UTC, KhYulian commented on controllers/contacts.controller.js
> +  const movie = await db.listContacts({ limit });
movie?

2023-01-07 22:25 UTC, KhYulian commented on controllers/contacts.controller.js
> +async function getContactId(req, res, next) {
getContactById / getContact

2023-01-07 22:25 UTC, KhYulian commented on controllers/contacts.controller.js
> +async function getContactList(req, res, next) {
getContacts

2023-01-07 22:25 UTC, KhYulian commented on controllers/contacts.controller.js
> +const db = require("../models/contacts");
Зроби деструктуризацію

2023-01-07 22:26 UTC, KhYulian commented on helpers/index.js
> +}
Використовуй класи

2023-01-07 22:26 UTC, KhYulian commented on models/contacts.js
> +const listContacts = async ({ limit = 0 }) => {
getContacts / getContactsService

2023-01-07 22:27 UTC, KhYulian commented on schemas/index.js
> +const addMoviesSchema = Joi.object({
Чому movies, коли у нас contacts?)) Помітив це вже кілька разів. Виправ усюди

2023-01-07 22:28 UTC, KhYulian commented on schemas/index.js
> +
додай окрему схему для оновлення контаккту також

2023-01-07 22:28 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-07 22:28 UTC, KhYulian commented
Відповідай на коменти по мірі виправлення :)

2023-01-07 23:04 UTC, AndriiBeznosov commented on controllers/contacts.controller.js
> +  const movie = await db.listContacts({ limit });
Корегування вніс.

2023-01-07 23:05 UTC, AndriiBeznosov commented on controllers/contacts.controller.js
> +async function getContactId(req, res, next) {
Корегування вніс

2023-01-07 23:05 UTC, AndriiBeznosov commented on controllers/contacts.controller.js
> +async function getContactList(req, res, next) {
Корегування вніс

2023-01-07 23:08 UTC, AndriiBeznosov commented on controllers/contacts.controller.js
> +const db = require("../models/contacts");
Корегування вніс

2023-01-07 23:12 UTC, AndriiBeznosov commented on models/contacts.js
> +const listContacts = async ({ limit = 0 }) => {
Корегування вніс

2023-01-07 23:15 UTC, AndriiBeznosov commented on schemas/index.js
> +const addMoviesSchema = Joi.object({
Корегування вніс.

2023-01-07 23:21 UTC, AndriiBeznosov commented on schemas/index.js
> +
Корегування вніс.

2023-01-09 16:57 UTC, AndriiBeznosov commented on helpers/index.js
> +}
Вніс корегування використовуючи класи

2023-01-10 06:05 UTC, KhYulian approved these changes
Чудова робота

2023-01-10 06:05 UTC, merged