Hw04 auth
AndriiBeznosov/nodejs-homework-rest-api pull request #3
Opened 2023-01-22 02:45 UTC by AndriiBeznosov

Привіт. Перевір, будь ласка, 4 роботу.

2023-01-22 16:42 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-22 16:42 UTC, KhYulian commented on .env
> +JWT_SECRET=secret@12345!
.env додайте в gitignore та видаліть з репозиторію

2023-01-22 16:42 UTC, KhYulian commented on src/app.js
>  const formatsLogger = app.get("env") === "development" ? "dev" : "short";
const formatsLogger помістіть після імпортів

2023-01-22 16:42 UTC, KhYulian commented on src/app.js
> +  res.status(err.code).json({ message: err.message });
err.code || 500 має бути дефолтне значення

2023-01-22 16:42 UTC, KhYulian commented on src/controllers/contacts.controller.js
> +  if (Object.keys(req.query).includes("favorite")) {
для валідації полів використовуйте окрему middleware, яка спрацтовуватиме перед контроллером

2023-01-22 16:42 UTC, KhYulian commented on src/controllers/contacts.controller.js
> +      favorite: req.query.favorite,
А якщо favorite не було передано в  запиті? Тоді ви будете шукати контакти у яких поле favorite: undefined

2023-01-22 16:42 UTC, KhYulian commented on src/controllers/contacts.controller.js
> +      favorite: req.query.favorite,
Потрібно додавати favorite до фільтру лише якщо favorite заданий

2023-01-22 16:42 UTC, KhYulian commented on src/controllers/users.controller.js
> +    res.status(204).json({ status: "No Content" });
Якщо статус 204, то в response body нічого не повертається. Або використовуйте статус 200 або json замініть на .end()

2023-01-22 16:52 UTC, AndriiBeznosov commented on .env
> +JWT_SECRET=secret@12345!
корегування вніс. Дякую!

2023-01-22 16:53 UTC, AndriiBeznosov commented on src/app.js
>  const formatsLogger = app.get("env") === "development" ? "dev" : "short";
корегування вніс. Дякую!

2023-01-22 16:54 UTC, AndriiBeznosov commented on src/app.js
> +  res.status(err.code).json({ message: err.message });
корегування вніс.

2023-01-22 17:00 UTC, AndriiBeznosov commented on src/controllers/contacts.controller.js
> +      favorite: req.query.favorite,
поле favorite в нас можу бути true або false
якщо поле не вказано, я додав значення по дефолту, так можна лишити?


const getContactsService = async ({
  limit = 0,
  page = 0,
  favorite = [true, false],
}) => {
  try {
    const skip = (page - 1) * limit;
    const contacts = await Contacts.find({ favorite }).skip(skip).limit(limit);
    return contacts;
  } catch (error) {
    throw new HttpError("Not found", 404);
  }
};

2023-01-22 17:03 UTC, AndriiBeznosov commented on src/controllers/users.controller.js
> +    res.status(204).json({ status: "No Content" });
корегування вніс.

2023-01-22 18:14 UTC, AndriiBeznosov commented on src/controllers/contacts.controller.js
> +  if (Object.keys(req.query).includes("favorite")) {
корегування вніс.

2023-01-23 07:34 UTC, KhYulian commented on src/controllers/contacts.controller.js
> +      favorite: req.query.favorite,
Можете залишити так, але якщо у вас в базі будуть контакти в яких не задано поле favorite, то ваша query такі документи проігнорує

2023-01-23 07:35 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-23 07:35 UTC, merged